# Generated by Django 5.1.2 on 2024-10-19 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_contato_image_contato_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contatos.categoria'),
        ),
    ]
