# Generated by Django 5.1.2 on 2024-10-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_alter_contato_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria'},
        ),
    ]
